version: '3'
services:
  srcbot:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: "your_api_id_here"
      API_HASH: "your_api_hash_here"
      BOT_TOKEN: "your_bot_token_here"
      SESSION: "your_pyrogram_session_here"
      AUTH: "bot_owner_user_id_here"
      FORCESUB: "public_channel_username_here"
